
export const LOADING_ALLPARTIES="allparties/LOADING_ALLPARTIES";
export const SUCCESS_ALLPARTIES="allparties/SUCCESS_ALLPARTIES";
export const ERROR_ALLPARTIES="allparties/ERROR_ALLPARTIES";

export const GET_ALLPARTIES="allparties/GET_ALLPARTIES";
export const UPDATE_ALLPARTIES="allparties/UPDATE_ALLPARTIES";
export const DELETE_ALLPARTIES="allparties/DELETE_ALLPARTIES";
export const INDUVIDUAL_ALLPARTIES="allparties/INDUVIDUAL_ALLPARTIES";
