export const LOADING_PURCHASE_RETURN = "parties/LOADING_PURCHASE_RETURN";
export const SUCCESS_PURCHASE_RETURN = "parties/SUCCESS_PURCHASE_RETURN";
export const ERROR_PURCHASE_RETURN = "parties/ERROR_PURCHASE_RETURN";

export const GET_PURCHASE_RETURN = "parties/GET_PURCHASE_RETURN";
export const UPDATE_PURCHASE_RETURN = "parties/UPDATE_PURCHASE_RETURN";
export const DELETE_PURCHASE_RETURN = "parties/DELETE_PURCHASE_RETURN";
