export const LOADING_SALE_INVOICE="saleInvoice/LOADING_SALE_INVOICE";
export const SUCCESS_SALE_INVOICE="saleInvoice/SUCCESS_SALE_INVOICE";
export const ERROR_SALE_INVOICE="saleInvoice/ERROR_SALE_INVOICE";

export const GET_SALE_INVOICE="saleInvoice/GET_SALE_INVOICE";
export const UPDATE_SALE_INVOICE="saleInvoice/UPDATE_SALE_INVOICE";
export const DELETE_SALE_INVOICE="saleInvoice/DELETE_SALE_INVOICE";


