export const LOADING_PURCHASE_REPORT="parties/LOADING_PURCHASE_REPORT";
export const SUCCESS_PURCHASE_REPORT="parties/SUCCESS_PURCHASE_REPORT";
export const ERROR_PURCHASE_REPORT="parties/ERROR_PURCHASE_REPORT";

export const GET_PURCHASE_REPORT="parties/GET_PURCHASE_REPORT";
export const UPDATE_PURCHASE_REPORT="parties/UPDATE_PURCHASE_REPORT";
export const DELETE_PURCHASE_REPORT="parties/DELETE_PURCHASE_REPORT";


