export const LOADING_PURCHASEORDER="parties/LOADING_PURCHASEORDER";
export const SUCCESS_PURCHASEORDER="parties/SUCCESS_PURCHASEORDER";
export const ERROR_PURCHASEORDER="parties/ERROR_PURCHASEORDER";

export const GET_PURCHASEORDER="parties/GET_PURCHASEORDER";
export const UPDATE_PURCHASEORDER="parties/UPDATE_PURCHASEORDER";
export const DELETE_PURCHASEORDER="parties/DELETE_PURCHASEORDER";
export const INDUVIDUAL_PURCHASEORDER="parties/INDUVIDUAL_PURCHASEEORDER";
